### ISSUE TITLE
How to include indels in the input file?

### ISSUE THREAD

**Issue by snoopy-448** [im3sanger/dndscv#1]
HI,
I want to put indels in my input file, and I also see that dndscv can manage indels. But I don't know the exact format for indel.
For example, if there is an insertion(GG) between chr1:12345(A) and chr1:12346(T), how should I write them?
And how about deletions? Could you please give some explanations in the vignette?
 THANKS!

Yang

**Comment by im3sanger** [comment]
Hi Yang,

The input format for indels is quite flexible. An indel will be counted in the model as long as the position recorded in the input table of mutations falls within the coding sequence (or a splice site) of a gene. This will probably change in a future version, to better account for long indels starting in an intron and ending in an exon.

I would suggest the following format for the GG insertion that you use as an example:
chr1	12345	A	AGG

And the following format for an example deletion of 5 bases:
chr1	12345	ATGCG	-

Best,
Inigo
