### ISSUE TITLE
Error when using target sequencing sample

### ISSUE THREAD

**Issue by JJMaggie** [im3sanger/dndscv#10]
hello,

I am trying to use dNdScv on target sequencing sample, I get the error message

```
> dndscvout=dndscv(muts_table, gene_list=NULL, max_muts_per_gene_per_sample=Inf, max_coding_muts_per_sample=Inf, min_indels=5, refdb="hg19", cv="hg19")
[1] Loading the environment...
[2] Annotating the mutations...
[3] Estimating global rates...
[4] Running dNdSloc...
[5] Running dNdScv...
Error in while ((it <- it + 1) < limit && abs(del) > eps) { :
  missing value where TRUE/FALSE needed
Calls: dndscv
In addition: Warning messages:
1: glm.fit: algorithm did not converge
2: glm.fit: fitted rates numerically 0 occurred
3: glm.fit: algorithm did not converge
4: glm.fit: fitted rates numerically 0 occurred
5: glm.fit: fitted rates numerically 0 occurred
Execution halted
```
What parameters do I need to adjust？

Many Thanks
Maggie

[muts_table.txt](https://github.com/im3sanger/dndscv/files/2197121/muts_table.txt)

**Comment by im3sanger** [comment]
Dear Maggie,

Please note that when analysing targeted data (i.e. not whole-exome or whole-genome data), you need to input the list of genes sequenced in the experiment (using the parameter gene_list=).

If this does not solve the problem, could you please send me an example table of mutations that I can use to reproduce this error?

Best wishes,
Inigo

**Comment by JJMaggie** [comment]
hi Inigo,

   Thanks for your reply. I add the gene_list parameter, but the error is same.

   This is my gene_list:

```
dndscvout=dndscv(muts_table, gene_list=c("ABCA1","ABCC1","ABCC4","ABCD2","ABCG1","ADAMTS20","ADCY8","AMPD1","APC","ARL17A","BCL9L","CHRM2","CRB3","CTNNB1","DLG1","EGFR","EHMT2","ENPP3","EZH2","FAM153A","FAM153B","FERMT1","FLT3LG","FOXA1","FRMD3","FRMD5","FRMD6","FRMD8","GOLGA8K","HNF1A","HOXA5","HOXA7","HOXB13","HOXB9","HOXD4","HS6ST1","HYPK","IRS1","KRAS","LGR5","LGR6","LLGL2","LRRC37A2","MAP2K7","MPP5","MRPS25","MSH5","MUC4","MYC","MYH2","MYO10","MYO7A","NBPF20","NPIPB5","NR2C2","PABPC3","PAK1","PAK4","PARD3","PARP1","PARP2","PARP3","PARP4","PCDHB13","PRDM9","PREX2","PRKCI","PRKCZ","RAF1","RNF175","SCRIB","SERF2","SETD8","SGCZ","SMAD3","SPANXN1","SPHKAP","SRC","SRP19","STK19","TCHH","TRIM49","ZNF57"), max_muts_per_gene_per_sample=Inf, max_coding_muts_per_sample=Inf, min_indels=5, refdb="hg19", cv="hg19")
````

    Is it a problem with this sample? I analyzed 51 samples, 27 of which had results, and 24 of them were such mistakes.

Many Thanks
Maggie

**Comment by im3sanger** [comment]
Hi Maggie,

I am confused. Are you feeding individual samples separately to dndscv? dNdScv normally needs a cohort of samples as input. For example, if you need to find genes under positive selection in a cancer type for which you have 51 samples, you should collect all of the mutations in a single table as input for dndscv.

Feel free to send me an email with a reproducible example so that I can better understand what the problem is.

Best wishes,
Inigo
