### ISSUE TITLE
an execution error

### ISSUE THREAD

**Issue by vegetableyu** [im3sanger/dndscv#103]
Hi there,
    I encountered an error while running dndscv. The log shows:
[1] Loading the environment...
[2] Annotating the mutations...
    Note: 10 samples excluded for exceeding the limit of mutations per sample (see the max_coding_muts_per_sample argument in dndscv). 136 samples left after filtering.
    Note: 25 mutations removed for exceeding the limit of mutations per gene per sample (see the max_muts_per_gene_per_sample argument in dndscv)
    62% ...
[3] Estimating global rates...
[4] Running dNdSloc...
[5] Running dNdScv...
    Regression model for substitutions (theta = 2.4).
Error in data.frame(gene_name = genemuts$gene_name, n_syn = genemuts$n_syn,  : 
  arguments imply differing number of rows: 19216, 0, 1
Calls: dndscv -> data.frame
In addition: Warning messages:
1: In dndscv(mutations, refdb = "RefCDS_human_GRCh38_GencodeV18_recommended.rda") :
  Mutations observed in contiguous sites within a sample. Please annotate or remove dinucleotide or complex substitutions for best results.
2: In dndscv(mutations, refdb = "RefCDS_human_GRCh38_GencodeV18_recommended.rda") :
  Same mutations observed in different sampleIDs. Please verify that these are independent events and remove duplicates otherwise.
3: In model$y == genemuts$n_syn :
  longer object length is not a multiple of shorter object length
Execution halted

My command is: 
library("dndscv")
library(Biostrings)
args = commandArgs(trailingOnly=TRUE)
mutations = read.table(args[1] , header=T, colClasses=c("character","character","numeric","character","character"))
dndsout = dndscv(mutations, refdb="RefCDS_human_GRCh38_GencodeV18_recommended.rda")

the input file format is:
sampleID        chr     pos     ref     mut
ZS    1       2025017 A       T
ZS    1       6106482 T       A
ZS    1       10653992        T       A
ZS    1       15461811        A       T
ZS    1       15493076        T       A
ZS    1       16026369        T       A
ZS    1       16138221        C       T
ZS    1       17093625        T       A

I hope you can give some advice, thank you very much for your help!

**Comment by KevinZhou-hub** [comment]
Hi there! I encountered the same error "Error in data.frame(gene_name = genemuts$gene_name, n_syn = genemuts$n_syn, :arguments imply differing number of rows: 19216, 0, 1", did you solve this? Thank you!
