### ISSUE TITLE
confidence intervals for gene-level dN/dS values and version for hg38

### ISSUE THREAD

**Issue by AlinaSc** [im3sanger/dndscv#13]
Hi, 

I was just wondering if it is somehow possible to easily obtain gene level confidence intervals for the dN/dS values? 
And also, is there a version of the package for hg38?
Hope you can help me!

Best, 
Alina

**Comment by im3sanger** [comment]
Hi Alina,

Thank you for your interest in dNdScv.

At present, only maximum likelihood estimates are provided for the dN/dS values at gene level. I will add your request to calculate confidence intervals to the list of future improvements.

At present, there is only support for hg37 but offering a general implementation of dndscv for any assembly or any species is a top priority for me. For now, you can use liftover to move your hg38 variants to hg37 to run dndscv.

Best wishes,
Inigo
