### ISSUE TITLE
Error in while ((it <- it + 1) < limit && abs(del) > eps) { :    missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by AlfredShawn** [im3sanger/dndscv#14]
Hi, 

I tried to run dndscv against the TCGA legacy maf files for several cancer types. Here is my code:
query.stad.hg19.maf <- GDCquery(project = "TCGA-STAD", 
                                data.category = "Simple nucleotide variation", 
                                data.type = "Simple somatic mutation",
                                access = "open", 
                                file.type = "gsc_STAD_pairs.aggregated.capture.tcga.uuid.automated.somatic.maf",
                                legacy = TRUE)
GDCdownload(query.stad.hg19.maf)
stad.hg19.maf <- GDCprepare(query.stad.hg19.maf)

selection.df <- stad.hg19.maf %>% 
  mutate(submitter_id = gsub("^(TCGA\\-\\w+\\-\\w+)\\-\\w+\\-\\w+\\-\\w+\\-\\w+","\\1",Tumor_Sample_Barcode, perl=TRUE)) %>%
  dplyr::select(submitter_id, Chromosome, Start_Position, Reference_Allele, Tumor_Seq_Allele1) %>%
  rename(sampleID = submitter_id, chr = Chromosome, pos = Start_Position, ref = Reference_Allele, mut = Tumor_Seq_Allele1) %>%
  mutate(chr=gsub("^chr(\\w+)","\\1",chr, perl=TRUE))

stad.dndsout <- dndscv(selection.df)

But I encountered an error said: 
Error in while ((it <- it + 1) < limit && abs(del) > eps) { : 
  missing value where TRUE/FALSE needed

I read some posts which said the missing value error is from glm.nb. Could you tell me how should I filter and prepare my input so I can avoid such errors? Thanks.

Best,

Yu

**Comment by zx8754** [comment]
Maybe this is a different issue, but when I don't specify the gene list, then I get below error:

```R
dndsout <- dndscv(dat)
[1] Loading the environment...
[2] Annotating the mutations...
    Note: 1 mutations removed for exceeding the limit of mutations per gene per sample
[3] Estimating global rates...
[4] Running dNdSloc...
[5] Running dNdScv...
    Regression model for substitutions: no covariates were used (theta = 0.0108).
Error in glm.fitter(x = X, y = Y, w = w, etastart = eta, offset = offset,  : 
  NA/NaN/Inf in 'x'
```

**Comment by im3sanger** [comment]
Hello,

Apologies for the slow response. This seems to a problem with glm.nb sometimes yielding an error and crashing dndscv. I just modified the way this is handled in dNdScv, thanks to a suggestion from a user.

Please install the latest version and let me know if this problem persist. I am closing the issue now, but please reopen it if needed.

Inigo

**Comment by laloverdin** [comment]
Hello,
I am getting this error when trying to use the GRCh38 found in your data "https://github.com/im3sanger/dndscv_data/tree/master/data"

**Comment by laloverdin** [comment]
Hello again,  @im3sanger. I found the error was regarding to the chromosome names as "1", "2"... while the GRCh38 convention in Ensembl is using the chr prefix: "chr1", "chr2".
I added the "chr" and it works fine now.
Thanks
