### ISSUE TITLE
length(e1) not a multiple length(e2)

### ISSUE THREAD

**Issue by fpbarthel** [im3sanger/dndscv#15]
https://github.com/im3sanger/dndscv/blob/837eaa188757649805ab694f8fe0ddffb358709d/R/dndscv.R#L187

This line throws a tantrum on some of my data:

```
> any(pos == RefCDS[[geneind]]$intervals_splice)
Error in if (n1%%n2) warning("length(e1) not a multiple length(e2)") : 
  argument is not interpretable as logical
```

Looks like because its referencing an empty object

```
> RefCDS[[geneind]]$intervals_splice
numeric(0)
```

So fairly easy to fix as follows:
```
> length(RefCDS[[geneind]]$intervals_splice) > 0 && any(pos == RefCDS[[geneind]]$intervals_splice)
[1] FALSE
```

**Comment by im3sanger** [comment]
Thank you for raising this up and proposing a solution. Would it be possible for you to send me a reproducible example that I can try to better understand this? Perhaps simply the mutation that led to this error?

Thanks,
Inigo

**Comment by fpbarthel** [comment]
Yes. Using the following data frame as inout to `dndscv()` should trigger this error:


sampleID | chr | pos | ref | mut
-- | -- | -- | -- | --
a | 10 | 115312925 | T | C
b | 10 | 114910854 | C | T
c | 10 | 112838833 | C | G

**Comment by im3sanger** [comment]
Hello,

Thanks again for raising this up. I have looked into this and the fix proposed does not seem to be the solution for your example dataset. In fact, any(1==numeric(0)) does not through an error. Instead, as far as I can see, the error seems to occur when the input dataset does not contain any coding substitution. I have updated the dndscv function accordingly to provide a more informative error message and stop the execution of dndscv when no valid substitutions are found.

If you get this error under other circunstances, please do let me know.

Many thanks,
Inigo

**Comment by fpbarthel** [comment]
Thanks for looking into this! Did the example dataset not trigger this error for you? I don’t know it’s the lack of coding substitutions in this input because the error initially occurred using a dataset with 1mln rows, I just pulled out these three as a minimum reproducible subset. Would it help if I expanded the example?

**Comment by im3sanger** [comment]
Yes, your example triggered the error, but the fix you suggested did not fix it since it was caused by an absence of coding substitutions. Another user also got this error and it was also caused by an absence of coding substitutions (he was using indels only). But this may not be the problem if you get this error with 1M mutations....

If you could expand the example including some coding mutations, that would be very helpful. You could also try installing the latest version of dndscv to see if the changes fix your error.

Thanks!

**Comment by fpbarthel** [comment]
This is some really weird behavior. Indeed, `any(1==numeric(0))` evaluates to `FALSE` so it doesn't make sense for this to trigger an error yet it is happening here. So I copied the `dndscv()` function statement and added some debugging code (using a fresh `devtools::install_github` install as of an hour ago):

```
  for (j in 1:nrow(mutations)) {
    geneind = mutations$geneind[j]
    pos = mutations$pos[j]
    message("j = ", j, ", geneind= ", geneind, " pos = ", pos, " RefCDS[[geneind]]$intervals_splice length = ", length(RefCDS[[geneind]]$intervals_splice))
    message("eval test = ", any(pos == RefCDS[[geneind]]$intervals_splice))
```

Here is the output:

```
> dnds = dndscv(df, refdb = "hg19")
[1] Loading the environment...
[2] Annotating the mutations...
    Note: 7 mutations removed for exceeding the limit of mutations per gene per sample
j = 1, geneind= 6723 pos = 135438925 RefCDS[[geneind]]$intervals_splice length = 15
eval test = FALSE
j = 2, geneind= 12469 pos = 135203152 RefCDS[[geneind]]$intervals_splice length = 30
eval test = FALSE
j = 3, geneind= 2924 pos = 135140451 RefCDS[[geneind]]$intervals_splice length = 15
eval test = FALSE
...
j = 83, geneind= 2189 pos = 115905471 RefCDS[[geneind]]$intervals_splice length = 70
eval test = FALSE
j = 84, geneind= 11629 pos = 115381925 RefCDS[[geneind]]$intervals_splice length = 205
eval test = FALSE
j = 85, geneind= 7674 pos = 115338409 RefCDS[[geneind]]$intervals_splice length = 60
eval test = FALSE
j = 86, geneind= 7674 pos = 115312925 RefCDS[[geneind]]$intervals_splice length = 60
eval test = FALSE
j = 87, geneind= 17295 pos = 114910854 RefCDS[[geneind]]$intervals_splice length = 70
eval test = FALSE
j = 88, geneind= 664 pos = 112838833 RefCDS[[geneind]]$intervals_splice length = 0
Error in if (n1%%n2) warning("length(e1) not a multiple length(e2)") : 
  argument is not interpretable as logical
In addition: Warning message:
In dndscv(df, refdb = "hg19") :
 Error in if (n1%%n2) warning("length(e1) not a multiple length(e2)") : 
  argument is not interpretable as logical 
```

As you can see, the loop runs for a few cycles then exits with an error. This seems to occur when `RefCDS[[geneind]]$intervals_splice length = 0`. Interestingly, here it is not the `if (any(pos == RefCDS[[geneind]]$intervals_splice))` that triggers the error but the `message("eval test = ", any(pos == RefCDS[[geneind]]$intervals_splice))` since it's not printing the message.

**Comment by fpbarthel** [comment]
AH I think it has to do with pos being of the `integer64` type:

```
> mutations$pos[88]
integer64
[1] 112838833
> mutations$pos[88] == RefCDS[[geneind]]$intervals_splice
Error in if (n1%%n2) warning("length(e1) not a multiple length(e2)") : 
  argument is not interpretable as logical
```

**Comment by im3sanger** [comment]
Hmm, interesting, thanks. I have never come across this before. Is that because you used the integer64 format instead of numeric (double) format when loading your mutation table? Or is this something that other users are likely to experience? Just trying to understand whether I should make any changes to dndscv. I guess I could always convert the pos column to numeric format inside dndscv?

**Comment by fpbarthel** [comment]
I didn't explicitly specify `integer64` type, the data came that way when I loaded it from a database using `dbGetQuery()`, so I didn't realize this was the cause of the error until now (and had no idea that it was in the integer64 format and not numeric!!). So I guess it may be useful to others make a minor change? Another option perhaps would be to check if the input is of the right type and to output a warning but make the conversion anyway?

**Comment by im3sanger** [comment]
I just fixed this to avoid this problem in the future. Many thanks for raising this up and figuring out the root of the problem. I hope dndscv proves useful in your analyses.

Best,
Inigo
