### ISSUE TITLE
Different chromosome format in hg19 and hg38 rda file

### ISSUE THREAD

**Issue by slzhao** [im3sanger/dndscv#17]
Please see example below. Would you please fix it?

data("refcds_hg19", package="dndscv")
RefCDS [[1]]$chr
"19"

load("RefCDS_human_GRCh38.p12.rda")
RefCDS[[1]]$chr
"chr19"

I will suggest adding something like this in the function:
genomePkgStype=seqlevelsStyle(sapply(RefCDS,function(x) x$chr))
seqlevelsStyle(mutations[,2])=genomePkgStype

**Comment by im3sanger** [comment]
Hello,

Thanks for this. I am not sure I understand this request. To avoid unnecessary dependencies and make the functions applicable to any genome, including files not in Ensembl, I decided to retain the chromosome names used in the fasta files used as reference. The user only has to ensure that the mutation table uses the same chromosome names than the reference genome... Does this make sense? Apologies if I misunderstood this request. I can certainly remove the "chr" prefix for GRCh38 if it helps, but I did not think that this should be a problem.

Best wishes,
Inigo

**Comment by slzhao** [comment]
Hello Inigo,

Thanks for your reply. My question/request is that why hg19 and hg38 database in dndscv had different style (one with and one without "chr"). I totally understand your decision on this as with or without "chr" is not a major issue.

I was using dndscv in different data sets in hg19 and hg38, and tried to run it automatically so didn't want to manually adjust with or without "chr" every time as the style of hg19 and hg38 database in dndscv are different. The example codes are how I deal with data sets with or without "chr" automatically and let them match the style of dndscv database (RefCDS). 

So just my suggestion on it. Never mind.

Best,
Shilin

**Comment by im3sanger** [comment]
Hi Shilin,

Thanks for explaining this in more detail. I understand what you mean. The only reason why the chr names are different in the RefCDS between both builds is that I retained the name they had in the fasta file that I used to create them (using buildref.R). However, I could certainly remove the "chr" prefix from the GRCh38 object available publicly if that helps...

Inigo
