### ISSUE TITLE
No p values or q values calcuated

### ISSUE THREAD

**Issue by juansearch** [im3sanger/dndscv#2]
Dear im3sanger,
I'm very exited to run this method on my data. I have a small list of <200 somatic mutations identified using Mutect. I tried running dndscv on the variant list, and no p values nor q values come out in the results. Here is the output for the dndscv(input) call:
[1] Loading the environment...
[2] Annotating the mutations...
[3] Estimating global rates...
[4] Running dNdSloc...
[5] Running dNdScv...
    Regression model for substitutions: no covariates were used (theta = 21.6).
Warning messages:
1: glm.fit: fitted rates numerically 0 occurred 
2: In theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace = control$trace >  :
  iteration limit reached
3: In theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace = control$trace >  :
  iteration limit reached
The output has the following columns:
      gene_name n_syn n_mis n_non n_spl wmis_cv wnon_cv wspl_cv  pmis_cv ptrunc_cv pallsubs_cv qmis_cv qtrunc_cv qallsubs_cv

**Comment by im3sanger** [comment]
Dear Juan,

Thank you for your interest in dNdScv.

I have never seen this error before. Could you send me your table of mutations or another dataset that I can use to reproduce this error? (see my GitHub profile for contact details)

Best wishes,
Inigo

**Comment by im3sanger** [comment]
Dear users,

I replied privately to Juan in December, but I would like to record the answer here in case it is useful for other users.

When running dNdScv with an input mutation table that does not contain indels, the global p-value and q-value columns from the method are "pallsubs_cv" and "qallsubs_cv" (not "pglobal_cv" or "qglobal_cv", which reflect the integrated p-values of substitutions and indels). I will make this clear in future versions of the tutorial.

Best wishes,
Inigo
