### ISSUE TITLE
Positional shift if mutations$pos input column has factor levels

### ISSUE THREAD

**Issue by MaximilianStammnitz** [im3sanger/dndscv#22]
Hi,

dndscv.R line 47: mutations[,3] = as.numeric(mutations[,3]) 

Shifts positions if the corresponding input column has factor levels. Was surprised to find that > 70% of my SNVs didn't agree with the actual reference base at first... :-)

mutations[,3] = as.numeric(as.character(mutations[,3])) will fix it.

Best,
Max

**Comment by im3sanger** [comment]
Fixed! Thanks Max.
