### ISSUE TITLE
dndscv.R line 147, GenomicRanges::findOverlaps

### ISSUE THREAD

**Issue by MaximilianStammnitz** [im3sanger/dndscv#23]
Hiya,

dndscv.R line 147: ol = as.matrix(GenomicRanges::findOverlaps(gr_muts, gr_genes, type="any", select="all”)) stopped for me while raising the following error message:

Error in as.vector(data) : no method for coercing this S4 class to a vector 
5 as.vector(data) 
4 array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x), NULL) else NULL) 
3 as.matrix.default(GenomicRanges::findOverlaps(gr_muts, gr_genes, type = "any", select = "all")) 
2 as.matrix(GenomicRanges::findOverlaps(gr_muts, gr_genes, type = "any", select = "all"))
1 dndscv()

This could be easily circumvented with ol = as.data.frame(GenomicRanges::findOverlaps(gr_muts, gr_genes, type="any", select="all”)). 

I am not sure though why this doesn't seem to have troubled anyone else before.

Best,
Max

**Comment by im3sanger** [comment]
Fixed. Thanks Max. I will push the changes later today, together with other fixes to buildref and improvements to the buildref vignette.
