### ISSUE TITLE
Do I need these covariates for using dNdScv properly

### ISSUE THREAD

**Issue by beginner984** [im3sanger/dndscv#24]
Sorry, Could you please help me?

I have 42 patients with oesophageal adenocarcinomas; These patients have been grouped to responders and non-responders to chemotherapy. From whole genome sequencing of tumour versus normal tissues, I have .vcf files of somatic indels and snp for these patients. I want to know what is different in these patients that some of them respond to chemotherapy and some of them not. In this paper 

The landscape of selection in 551 esophageal adenocarcinomas defines genomic biomarkers for the clinic

They used  HiC (chromatin conformation), Gene expression and Replication timing data measured in cell lines as covariates in the analysis to calculated the expected background mutation rate. Likely that has been done in s slightly more advanced way with dNdScv to assess positive selection.

My question is, should I also use these covariates as they used for my specific question in this data? Does dNdScv  automatically do that for me?

Thanks a lot for this best performing tool

**Comment by im3sanger** [comment]
Hello,

In principle, you should be able to use the default covariates that come with the dNdScv package. Some (typically small) improvements can be obtained when using your own covariates, but I would not expect them to have a considerable effect on your results, given the details that you give in your question.

However, you may want to contact the authors of the paper that you mention (particularly Alex Frankell) to better understand their motivation for using their own covariates.

Best wishes,
Inigo
