### ISSUE TITLE
Unable to run dndscv

### ISSUE THREAD

**Issue by beginner984** [im3sanger/dndscv#25]
Sorry,

I  have converted .vcf file of somatic indel from one patients to tab delimited file by vcftools and this is the head and tail of my file

> tail(mut)
        chr      pos  sampleID ref    mut
1581 hs37d5 29710101 Sample_1    A AAGCTC
1582 hs37d5 29710101 Sample_1    A AAGCTC
1583 hs37d5 30880175 Sample_1    G GTAATC
1584 hs37d5 30880175 Sample_1    G GTAATC
1585 hs37d5 34268258 Sample_1    C CATTCT
1586 hs37d5 34268258 Sample_1    C CATTCT

> head(mut)
   chr      pos  sampleID ref  mut
1 chr1  7914928 Sample_1    A ATAC
2 chr1  7914928 Sample_1    A ATAC
3 chr1 15080062 Sample_1    A   AG
4 chr1 15080062 Sample_1    A   AG
5 chr1 16714609 Sample_1    C  CAT
6 chr1 16714609 Sample_1    C  CAT
> 

When I am trying to run dndscv I am getting this error

> dndsout = dndscv(mut)
[1] Loading the environment...
[2] Annotating the mutations...
Error in dndscv(mut) : 
  Zero coding substitutions found in this dataset. Unable to run dndscv.
In addition: Warning messages:
1: In dndscv(mut) : NAs introduced by coercion
2: In dndscv(mut) :
  1586 rows in the input table contained NA entries and have been removed. Please investigate.

Could you please help me in running your tool on my data?

Thanks a lot

**Comment by im3sanger** [comment]
Hello,

Please make sure that your columns are in the order shown in the tutorial, as dndscv expects this format as input: sampleID, chr, pos, ref, mut.

Hope this helps,
Inigo

**Comment by beginner984** [comment]
[fil.txt](https://github.com/im3sanger/dndscv/files/2853059/fil.txt)

Sorry, my columns are in the same order


```
> head(data)   sampleID  chr     pos ref mut 1 Sample_1 chrM   10373   G   A 2 Sample_1 chrM   14847   G   A 3 Sample_1 chrM   15892   T   C 4 Sample_1 chr1  782112   G   A 5 Sample_1 chr1 1026918   C   T 6 Sample_1 chr1 1133283   C   T
--
 
> | >
```
>

```
[1] Loading the environment...
[2] Annotating the mutations...
Error in dndscv(data) : 
  Zero coding substitutions found in this dataset. Unable to run dndscv.
In addition: Warning messages:
1: In dndscv(data) :
  Mutations observed in contiguous sites within a sample. Please annotate or remove dinucleotide or complex substitutions for best results.
2: In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
> View(covs)
> View(gr_genes)
Error in eval(call("@", object, slot)) : 
  no slot of name "elementType" for this object of class "GRanges"
> sel_cv = dndsout$sel_cv
Error: object 'dndsout' not found
> dndsout = dndscv(data)
[1] Loading the environment...
[2] Annotating the mutations...
Error in dndscv(data) : 
  Zero coding substitutions found in this dataset. Unable to run dndscv.
In addition: Warning messages:
1: In dndscv(data) :
  Mutations observed in contiguous sites within a sample. Please annotate or remove dinucleotide or complex substitutions for best results.
2: In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
```

**Comment by zx8754** [comment]
Related post at biostars:

 - [dNdScv error: Zero coding substitutions found in this dataset](https://www.biostars.org/p/363392/)

**Comment by beginner984** [comment]
Sorry 

This is my post in biostars

People says this tool only handles the SNV but I read this also can handle the indels

Could you please skim over my input file to see why I'm failing to run this tool ?

Thank you for any help
--------------------------------------------
On Tue, 2/12/19, Tokhir Dadaev <notifications@github.com> wrote:

 Subject: Re: [im3sanger/dndscv] Unable to run dndscv (#25)
 To: "im3sanger/dndscv" <dndscv@noreply.github.com>
 Cc: "beginner984" <izadi1991@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Tuesday, February 12, 2019, 7:33 AM
 
 Related post at biostars:
 
 dNdScv error: Zero
 coding substitutions found in this dataset
 
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by im3sanger** [comment]
Thanks. As you know, I posted the solution in biostars, but I leave the link here for other users:
https://www.biostars.org/p/363392/#363470
