### ISSUE TITLE
Getting unkown error on my indel file

### ISSUE THREAD

**Issue by beginner984** [im3sanger/dndscv#27]
Sorry;

I have a txt file of only indel from whole genome sequencing; I have tried to prepare my file for your software but I am permanently getting error. Could you please have a look at my file may be I could run this software on my idels
[
[indel.txt](https://github.com/im3sanger/dndscv/files/2877762/indel.txt)
](url)

```
> 
> dndsout = dndscv(mut) [1] Loading the environment... [2] Annotating the mutations... Error in dndscv(mut) :    Zero coding substitutions found in this dataset. Unable to run dndscv. In addition: Warning messages: 1: In dndscv(mut) :   Mutations observed in contiguous sites within a sample. Please annotate or remove dinucleotide or complex substitutions for best results. 2: In dndscv(mut) :   Same mutations observed in different sampleIDs. Please verify that these are independent events and remove duplicates otherwise.

```

**Comment by im3sanger** [comment]
Hello. As I mentioned in an earlier response, the reason for this result is that dNdScv cannot be run only on indels, it needs substitutions. Presumably, you have both substitutions and indels from the same samples, so you would need to combine them into a single file before running dNdScv.
