### ISSUE TITLE
other annotation file from hg19

### ISSUE THREAD

**Issue by arpoe** [im3sanger/dndscv#3]
Hi Iñigo,

I have tried to play around with the package, it looks very nice!  Now I would like to use another annotation file from hg19, but I did not quite understand how to prepare or from where to retrieve the required .rda file. I assume it is somehow converted from one of the standard protein annotation formats? 
Could you please help me out with this?

Thanks,
Anna

**Comment by im3sanger** [comment]
Hi Anna,

Thanks! Unfortunately, at the moment the package can only be run with its default hg19 annotation file. However, I am planning to add a function to build the reference .rda files for other species or transcript files in the near future. I will let you know as soon as this functionality is available. I hope it will be soon!

Best wishes,
Inigo

**Comment by mksamur** [comment]
Hi Inigo,
Have you had any update on GRCh38?
Best
Mehmet

**Comment by im3sanger** [comment]
Dear Mehmet,

I am afraid I do not have any updates on this yet.

Best wishes,
Inigo

**Comment by mksamur** [comment]
Thanks Inigo. I just used liftOver from 38 to 19 and modified line 238 in dndscv.R as warning and it works well now. I lost around 80 mutations out of 3M due to wrong base but it is fine with me. Thanks for creating such a great tool.

**Comment by im3sanger** [comment]
Many thanks Mehmet. I am glad this worked. I am planning to relax the strict way in which dndscv currently handles wrong reference bases to help with liftover cases and to output the list of mutations with wrong reference calls for further inspection.
