### ISSUE TITLE
Fail to load Tutorial

### ISSUE THREAD

**Issue by JenniferZhung** [im3sanger/dndscv#31]
Hi,
I can't load the tutorial message. Maybe something wrong with the link?
Could you please help me? 
Thx ~~
Jennifer

**Comment by im3sanger** [comment]
Hi Jennifer,

Please try again. If that does not work, you can go to http://htmlpreview.github.io/ and paste http://github.com/im3sanger/dndscv/blob/master/vignettes/dNdScv.html.

Alternatively, you can download the original html file from the link above and open it in your browser. But the link normally works well.

I hope it helps. Best wishes,
Inigo
