### ISSUE TITLE
how to estimate probabilities that variants in particular exons ？

### ISSUE THREAD

**Issue by feihongloveworld** [im3sanger/dndscv#39]
hi sir：
     <Universal Patterns of Selection in Cancer and Somatic Tissues>
     in this paper,there is a good idea:
    '''
Furthermore, with increasing numbers of tumors being sequenced, we will be able to deploy such reasoning at ever higher resolution to estimate probabilities that variants in particular exons or domains of a gene in a particular tumor type are driver mutations. Such approaches could ultimately underpin statistically rigorous, personalized annotation of driver mutations, a crucial step in successfully implementing precision oncology.
    '''
how to estimate probabilities that variants in particular exons with dndscv now ?
wating for you return .
thanks

**Comment by feihongloveworld** [comment]
@im3sanger  hi sir，can you help me ？ Tanks very much ....Waiting for your reply

**Comment by im3sanger** [comment]
Hello,

Sorry for the late response. With the current implementation of dndscv, perhaps the easiest way to do this would be to create a new RefCDS object (using the [buildref function](http://htmlpreview.github.io/?http://github.com/im3sanger/dndscv/blob/master/vignettes/buildref.html)), in which each entry is a separate exon. You can then find the expected rates per exon in dndsout$genemuts.

Alternatively, you could write a script that calculates the number of each trinucleotide in a given exon and multiply them by the mutation rate per trinucleotide, which is one of the outputs in the dndsout object. You could make this more or less sophisticated using or not using covariates.

I hope it helps,
Inigo

**Comment by feihongloveworld** [comment]
hi sir :
      can your team provide a release version with exion level analysis。
      because you  are more professional than me。
wating for you return 
best wishes
thanks

**Comment by im3sanger** [comment]
Hello,
Unfortunately, I am over-stretched at the moment, so it is unlikely that I will be able to do this in the near future. The example provided in the buildref tutorial may offer some clues. However, buildref is designed to discard transcripts that are not in frame and many exons will not be in frame. A solution would be to correct the start and end coordinates of each exon (trimming one or two bases as required) to work with in-frame exon segments.

In the next few months, we are planning to release a version of dndscv at the level of protein domains. While this is different from what you are asking, it may be more biologically meaningful and you may find it useful.

Best wishes,
Inigo
