### ISSUE TITLE
Global dNdS ratios very high >1000

### ISSUE THREAD

**Issue by tomsuntom** [im3sanger/dndscv#41]
Hi there,

First of all, I want to express my thanks for this amazing package! There are not many tools out there that can analyze somatic driver mutations on hg38. I really appreciate your work!

I have whole-exome data that I fed into the package. When I looked at the global dNdS ratio, it's very high >1000 instead of the ~1 per your paper. Why might this be? You can see my list of top genes and the global ratio screenshots. For some reason TTN shows up in the list, but it shouldn't right?

![Screen Shot 2019-12-15 at 8 37 29 PM](https://user-images.githubusercontent.com/42565156/70879616-e95ed980-1f7a-11ea-85b3-ebab51480f57.png)

![Screen Shot 2019-12-15 at 8 39 20 PM](https://user-images.githubusercontent.com/42565156/70879637-0398b780-1f7b-11ea-986d-41e87dceb4cd.png)

**Comment by im3sanger** [comment]
Hi Tom,

Thank you for your kind words and your interest in dNdScv.

From the information that you provide, it seems that the problem with your data is that (nearly) all synonymous mutations have been filtered out. This will yield dN/dS tending towards infinity. dNdScv needs all synonymous mutations to model mutation rates and so you will need to review your variant calling strategy to recover them. Sometimes, synonymous mutations are filtered out when working without matched normals. If your data is unmatched, this poses many challenges as the majority of synonymous mutations in unmatched analysis are germline SNPs.

Best wishes,
Inigo

**Comment by tomsuntom** [comment]
Hi Inigo,

You are so right! The maf file I worked with had all the synonymous mutations filtered out. I fixed that and now the global ratio is around ~1. YAY
