### ISSUE TITLE
theta.ml not converging

### ISSUE THREAD

**Issue by vodkatad** [im3sanger/dndscv#44]
Hello, I am using your package to compute dN/dS for a set of mutations derived from WGS - I am getting results but I am also seeing some warnings regarding a not converging model:
```
Warning messages:
1: In theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace = control$trace >  :
  iteration limit reached
2: In theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace = control$trace >  :
  iteration limit reached
```

I am in the same context of https://github.com/im3sanger/dndscv/issues/2, so no indels and "pallsubs_cv" and "qallsubs_cv" instead of pglobal/qglobal, which is fine...but I was wondering if I should worry about the lack of convergence of the negative binomial model - is it an issue?
Is this model used to gather dNdSloc and/or dNdScv values but not global ones (I suspect so since the warning does not appear with `outp=1`)? Does it concern only some genes with few mutations?

Thank you for your help, I am asking because I obtained some rather large CI[*] for the global dN/dS estimates and I am not sure if this is due to the number of variants that I'm using or other issues (this is not a plain list of somatic mutations):
> d$globaldnds
     name       mle      cilow   cihigh
wmis wmis 1.1040700 0.68095270 1.790096
wnon wnon 0.5496207 0.15496574 1.949353
wspl wspl 0.3074148 0.03863606 2.446001
wtru wtru 0.4598326 0.15155948 1.395135
wall wall 1.0467438 0.64715051 1.693072

Another thing that is puzzling me is the very low values but only for nonsense/splicing variants, since I do not understand how I could have a germline SNP contamination issue only for those ones....

**Comment by im3sanger** [comment]
Hi Elena,

Thank you for your interest in dndscv.

This is a relatively uncommon warning which I have sometimes seen when theta approaches very high values. Is your dataset very sparse by any chance? What value of theta do you get?

Since theta is estimated only for the negative regression model, this would not affect global dN/dS estimates or dNdSloc results, but it will affect dNdScv results. I have never seen this warning cause major problems before, so your results may be ok, but let me know if your significant genes look suspicious and I can look into this more carefully.

Best wishes,
Inigo

**Comment by im3sanger** [comment]
Just to clarify, the large confidence intervals that you are obtaining for the global dN/dS estimates are unaffected by the warning above and likely reflect that your dataset is quite small. How many coding mutations are you using, out of curiosity?

**Comment by vodkatad** [comment]
Hi, thank you taking the time to investigate this not properly code-related issue :)
My theta is
```
> print(dndsout$nbreg$theta)
[1] 17.68118
```
which considering the readme seemed ok to me, but probably it's too high.

The total numer of SVNs is 10997, but indeed I think that a small number of them turned out to be coding (which is somehow expected but I went straight to dndscv instead of cheking first with annovar/vep or other annotation tools this basic number :/):
```
> sum(dndsout$genemuts[,c(2,3,4,5)])
[1] 107
```
(we sit rightly on the ~1% exome/genome)
I suppose that this is really too sparse for a WGS - I should look into the basic genome distribution of these mutations to gather more insight (this was somehow expected but I did not reason from the beginning about the resulting small number of coding mutations...), then maybe restrict the analyses to the genes with at least a mutation to get a reasonable global dnds.

**Comment by im3sanger** [comment]
Hello,

Ok, this makes sense. dNdScv only uses coding variants, so with only 107 coding mutations exome wide you are getting relatively wide confidence intervals and a high theta. All of this is normal and not a problem, it simply reflects the sparsity of the data. I think that you can safely dismiss the warning about theta. If your data is whole-genome sequencing, you are doing the right thing by running dNdScv on the entire list of mutations to get global dN/dS estimates. You do not need to restrict the analysis to genes with mutations (in fact, you shouldn't, as it can introduce artificial biases on the estimates and it will not improve the confidence intervals).

Best wishes,
Inigo

**Comment by vodkatad** [comment]
OK, I see - thank you very much!
