### ISSUE TITLE
Can this tool find dN/dS values within regions of a gene? 

### ISSUE THREAD

**Issue by programmingprincess** [im3sanger/dndscv#45]
For instance, exon regions, or a particular amino acid sequence that is smaller than a gene--or is gene-level the smallest?

**Comment by im3sanger** [comment]
Hi Jiaqi Wu,

Thank you for your interest in dNdScv. Yes, this package has functionalities to analyse regions smaller than a gene. There are two main tools that you can use, but please send me an email for more details if you want:

1. Although it has not been advertised yet, a year ago I added two new functions to the package to study single site and single codon dN/dS: _sitednds_ and _codondnds_. There is a temporary [tutorial](http://htmlpreview.github.io/?http://github.com/im3sanger/dndscv/blob/master/vignettes/sitednds.html) on these functions, but we are working to document it better.
2. The dNdScv package also enables the user to create bespoke RefCDS databases. This means that you can run dNdScv on exons, protein domains, etc. by creating your own reference database. A tutorial on how to do this is [here](http://htmlpreview.github.io/?http://github.com/im3sanger/dndscv/blob/master/vignettes/buildref.html). We already have some of these objects precomputed.

There is also a function to run dNdScv on genesets (_genesetdnds_). Although most people use dNdScv with default settings, my intention was to create an environment where users can develop more complex applications.

I hope this helps,

Inigo
