### ISSUE TITLE
How could get NBR?

### ISSUE THREAD

**Issue by ChongJenniferZhang** [im3sanger/dndscv#46]
Hi inigo,

I have noticed you published a new great tool "NBR" to call noncoding drivers in PCAWG Nature paper. But I cannot find it anywhere in this page. Could you please tell me how to get it? 
Thank you so much.

Best,
Jennifer

**Comment by im3sanger** [comment]
Hi Jennifer,

My apologies. I am working to finish adapting and simplifying the original code and writing a tutorial to add NBR to the dNdScv package. In the meantime, please send me an email and I can share the original (unpolished) code that we used for the PCAWG paper.

Sorry for the inconveniences,
Inigo

**Comment by mjko1210** [comment]
Hi Inigo,

Thanks for this amazing tool! I'm also interested in running NBR to WGS data. Is it possible to try this out?  I'm very happy to hear that you are going to integrate this to dNdScv. 
My email address is mjko1210@gmail.com.
Thanks!
