### ISSUE TITLE
Error in names(x) <- value :    'names' attribute [10] must be the same length as the vector [9]

### ISSUE THREAD

**Issue by carladosanjos** [im3sanger/dndscv#48]
Dear Dr. Marticorena,

I've been been using the dndscv package successfully with the dadabase provided "hg19", however I am having ssues buildind a hg38 database with 'buildref' function. Here is what I got:

> buildref(cdsfile="~/genes/hg38.ncbiRefSeq.gtf", genomefile="~/hg38.fa", outfile = "hg38RefCDS.rda",excludechrs = "MT")
[1/3] Preparing the environment...
Error in names(x) <- value : 
  'names' attribute [10] must be the same length as the vector [9]

I was wondering if it has to anything to do with the 'cdsfile' format - what is the extension of such file? gff, gff3, gtf, fa?

Many thnaks for your help in advance!

Best wishes,

Carla

**Comment by im3sanger** [comment]
Hi Carla,

Thank you for your interest in dndscv. At the moment, gtf is not a valid input file for buildref. I would recommend following this tutorial on how to use buildref here:
http://htmlpreview.github.io/?http://github.com/im3sanger/dndscv/blob/master/vignettes/buildref.html

You can also download a RefCDS already generated for GRCh38 from this link:
https://github.com/im3sanger/dndscv_data/tree/master/data

Best wishes,
Inigo

**Comment by carladosanjos** [comment]
Many thanks! 

Best wishes
