### ISSUE TITLE
columns qmis_cv, qtrunc_cv, qallsubs_cv, pglobal_cv, qglobal_cv NA

### ISSUE THREAD

**Issue by guidmt** [im3sanger/dndscv#49]
Dear Dr. Marticorena,

I am trying to use your useful package, however, I get results in which the columns  qmis_cv, qtrunc_cv, qallsubs_cv, pglobal_cv, qglobal_cv are "NAs". The only column with some values is **pind_cv**.

![Screenshot 2020-05-27 at 22 38 31](https://user-images.githubusercontent.com/15264346/83074918-e3613e80-a06a-11ea-818a-9755b930af40.png)

I get also these warnings:

1: In dndscv(parse_maf_file, refdb = "/mnt/data/lab/gmt_data/pseudospace2/dNdScv/dndscv_data-master/data/RefCDS_human_GRCh38.p12.rda",  :
  Same mutations observed in different sampleIDs. Please verify that these are independent events and remove duplicates otherwise.
2: In model$y == genemuts$n_syn :
  longer object length is not a multiple of shorter object length

**edit: 28/05/2020**
I have done some tests, using the parameters cv=NULL I have resolved the "problem".
 
Many thanks in advance for your support, 

Guidantonio

**Comment by im3sanger** [comment]
Thank you, Guidantonio. Yes, I was going to suggest that. There are no covariates for GRCh38 yet (apologies), so "cv=NULL" needs to be used. Users can also generate their own covariates (e.g. coverage per gene in their data, expression level, etc). 

Best wishes,
Inigo
