### ISSUE TITLE
hg38 ref files

### ISSUE THREAD

**Issue by alhafidzhamdan** [im3sanger/dndscv#50]
Hi there, 

Sorry if i missed this but i'm struggling to generate my own hg38 refcds and covariate files. I wonder if you have already done this and if not where can i get "reference transcript table" and the rest of the epigenomic annotations (and do you have examples for in hg19 that use so that I could cross check formats)?

Al
Edinburgh

**Comment by im3sanger** [comment]
Hello,

I would recommend following this tutorial for buildref. This contains details on the input formats and where to find these files:
http://htmlpreview.github.io/?http://github.com/im3sanger/dndscv/blob/master/vignettes/buildref.html

You can also find a precomputed RefCDS in the link below:
https://github.com/im3sanger/dndscv_data/tree/master/data

I do not have covariates for GRCh38 yet, but you can use "cv=NULL" when running dndscv, as covariates can help sensitivity, but they are optional.

Best wishes,
Inigo
