### ISSUE TITLE
Regarding Zero coding substitutions found in this dataset. 

### ISSUE THREAD

**Issue by Smriti1990** [im3sanger/dndscv#52]
Hi, 
I am getting following error. Although I have checked in other posts as well but not able to solve it

Note: 1 samples excluded for exceeding the limit of mutations per sample (see the max_coding_muts_per_sample argument in dndscv). 0 samples left after filtering.
Error in dndscv(mut1) : 
  Zero coding substitutions found in this dataset. Unable to run dndscv. Common causes for this error are inputting only indels or using chromosome names different to those in the reference database (e.g. chr1 vs 1)
In addition: Warning message:
In dndscv(mut1) :
  Mutations observed in contiguous sites within a sample. Please annotate or remove dinucleotide or complex substitutions for best results.

But I have checked the chromosomes they are matching to the reference

![image](https://user-images.githubusercontent.com/23184365/84129741-fc50f300-aa5f-11ea-8564-56fe89929d59.png)

Can you please help me out.
Thanks

**Comment by im3sanger** [comment]
Hello,

It looks like your input table contains over 200,000 mutations, all from a single sample ("Sample_1"). This sample is being filtered out as an apparent hypermutator by the default parameters. Try using "max_muts_per_gene_per_sample = Inf, max_coding_muts_per_sample = Inf" as optional arguments when running dndscv to prevent any mutations and any samples from being excluded.

Best,
Inigo

**Comment by Smriti1990** [comment]
Thank you so much for helping out.
