### ISSUE TITLE
 Help troubleshooting metastasis analysis

### ISSUE THREAD

**Issue by carladosanjos** [im3sanger/dndscv#54]
Dear Inigo,

As for a pilot analysis I decided to run the dndScv to find the driver mutations of 20 metastasis from a single patient. The issue is the theta that is quite low:

>[1] Loading the environment...
[2] Annotating the mutations...
Same mutations observed in different sampleIDs. Please verify that these are independent events and remove duplicates otherwise.[3] Estimating global rates...
[4] Running dNdSloc...
[5] Running dNdScv...
    Regression model for substitutions: no covariates were used (theta = 0.0118).
    Regression model for indels (theta = 0.109)

> print(dndsout$globaldnds)
     name       mle     cilow   cihigh
wmis wmis 1.1713423 1.0336460 1.327382
wnon wnon 1.8306977 1.4429853 2.322584
wspl wspl 0.8365794 0.5846065 1.197156
wtru wtru 1.4050110 1.1406383 1.730659
wall wall 1.2011661 1.0613911 1.359348

> print(dndsout$nbreg$theta)
[1] 0.01180573

> sum(dndsout$genemuts[,c(2,3,4,5)])
[1] 1793

And also I got really high dN/dS values:

>print(dndsout$sel_cv[dndsout$sel_cv$qglobal_cv<0.1, c("gene_name", "wmis_cv", "wnon_cv", "wspl_cv", "wind_cv","qglobal_cv")])
      gene_name   wmis_cv    wnon_cv    wspl_cv  wind_cv   qglobal_cv
9751      MED13    0.0000  972.56149  972.56149   0.0000 0.000000e+00
19548    ZSWIM6    0.0000 2072.57843 2072.57843   0.0000 0.000000e+00
12472      PIGR    0.0000 2961.60884 2961.60884   0.0000 0.000000e+00
13415      PTEN    0.0000 4431.75002 4431.75002   0.0000 0.000000e+00
6988       GRM6    0.0000 1146.28027 1146.28027   0.0000 2.840391e-08
4472    DEFB112 1968.0664    0.00000    0.00000   0.0000 1.885530e-06
10209    MRPS33 1952.7419    0.00000    0.00000   0.0000 1.885530e-06
10731       NEB    0.0000   84.53213   84.53213   0.0000 3.432213e-05
16246     STK31    0.0000    0.00000    0.00000   0.0000 8.134051e-05
12379   PHACTR4    0.0000    0.00000    0.00000 183.8300 8.184216e-05
7367   HIST1H3F 1120.5645    0.00000    0.00000   0.0000 8.184216e-05
16888      TGM3    0.0000    0.00000    0.00000   0.0000 8.270763e-05
11185      NT5E    0.0000    0.00000    0.00000   0.0000 9.387596e-05
13863      RBP1  882.8510    0.00000    0.00000   0.0000 1.739435e-04
8936      LCE2D 1174.9042    0.00000    0.00000   0.0000 4.962280e-04
11604    OR4K15  604.9224    0.00000    0.00000   0.0000 2.642629e-03
12440    PI4K2A  377.4951    0.00000    0.00000   0.0000 4.270492e-03
10738   NECTIN1  329.8938    0.00000    0.00000   0.0000 7.770193e-03
5413       ESR1  310.8241    0.00000    0.00000   0.0000 7.770193e-03
6634      GLRA4  407.5595    0.00000    0.00000   0.0000 1.115215e-02
6226       FSHR  323.8849    0.00000    0.00000   0.0000 1.211753e-02
10290      MTBP  270.3075    0.00000    0.00000   0.0000 1.211753e-02
12085   PCDHA13  185.6039    0.00000    0.00000   0.0000 1.399733e-02
11925     PACS2  186.5174    0.00000    0.00000   0.0000 1.399733e-02
3692     COL3A1  141.5474    0.00000    0.00000   0.0000 3.170317e-02
5325       EPN2  245.2169    0.00000    0.00000   0.0000 3.170317e-02
18066     UBE3A  252.9915    0.00000    0.00000   0.0000 3.416394e-02
3647    CNTNAP5  156.4600    0.00000    0.00000   0.0000 3.719252e-02
13658     RABIF  612.7014    0.00000    0.00000   0.0000 4.593603e-02
8813   KRTAP4-7  108.2225    0.00000    0.00000 840.1972 6.646689e-02
5473    EXOC3L1    0.0000  413.39812  413.39812   0.0000 7.213474e-02
10593      NAV1  100.3460    0.00000    0.00000   0.0000 7.334158e-02
6564      GINS3    0.0000  463.56687  463.56687 511.9952 7.963213e-02
6594       GJE1  519.1427    0.00000    0.00000   0.0000 7.963213e-02

I would like to know why the model is not appropriate to my data - Should I consider the dnds_loc instead? Why am I getting so many significant drivers (34) with such high dN/dS ratio? Is it a data issue?

Many thanks!

Best wishes,

Carla

**Comment by im3sanger** [comment]
Hi Carla,

Thank you for your interest in dNdScv. Please accept my apologies for the very late response.

I know that you wrote to me later by email with a related query regarding collapsing duplicated mutations. Did that solve the problem above? 

Just in case it helps you or others, I will attempt to provide an answer here. From the description of your dataset and results, it sounds like you may have included the same mutations found in different metastases as independent events in the mutation table. This could explain both the very low theta values and many false positives. Briefly, if you input the same mutations many times, some genes will appear with too many synonymous mutations (leading to low theta, to try to explain the large variation in the synonymous rates across genes) while others will appear with too many non-synonymous mutations (looking like drivers). dNdScv assumes that all mutations in the input table are independent mutational events, so duplicated mutations should be removed from the input table (for example, using the same sampleID for samples from the same individual, and using the "unique" function in R to remove redundant entries).

Best wishes,
Inigo
