### ISSUE TITLE
Build Ref error

### ISSUE THREAD

**Issue by ggoodstudydaydayup** [im3sanger/dndscv#59]
Hi,
    I want to build a ref for other genome, but failed with error "Error in get(name, envir = asNamespace(pkg), inherits = FALSE) 
    NCList_find_overlaps_in_groups could not found". Then I remove IRanges, and could not install.
    Could you please tell me how to solve this problem?
    Thanks in advance.
Best wishes,
Liu

**Comment by ZM158** [comment]
Hello, I have the same problem. Have you solved it? Thank you
