### ISSUE TITLE
Very high dnds values

### ISSUE THREAD

**Issue by ArashDepp** [im3sanger/dndscv#66]
Hi.

I ran dndscv with hg19 based cancer mutation data with default parameters. However, I am observing that dn/ds ratio is shooting very high. For example, here is the distribution for dnds for mis-sense mutations (i.e wmis) across all genes. I removed outliers which even go upto 25000.
![image](https://user-images.githubusercontent.com/43116799/122602459-daaa2480-d040-11eb-97eb-57edd1e233a3.png)

Even retaining only the genes with q-value of mis-sense mutations < 0.1 gives roughly the same distribution.  Also the global estimate for mis-sense mutations is 450, which is way too higher than 1.

Could you help me to understand why this is the case?  Appreciate your time and help.

**Comment by ArashDepp** [comment]
Okay. I found a similar question by another user and the possible reason could be the lack of synonymous mutations in the data. 
I will keep it open for now and if introducing synonymous mutations solve this problem, then I will close it :)

**Comment by ArashDepp** [comment]
Yes indeed, the issue was lack of synonymous mutations in the input file. A quick tip for those who might be using maftools:
**mafObject@data** gives the nonsynonymous mutations
**mafObject@maf.silent** gives the silent/synonymous mutations
I used only the former by mistake.

**Comment by im3sanger** [comment]
Thank you, ArashDepp. I am closing this issue now as it seems to be solved, but do not hesitate to reopen it if needed.

Best,
Inigo
