### ISSUE TITLE
No qglobal_cv in "sel_cv"

### ISSUE THREAD

**Issue by KangWang0822** [im3sanger/dndscv#71]
Hi 

Very interesting tool to filter driver genes. But when I ran the dndscv() successfully, I did not find the  qglobal_cv in "sel_cv". Do you know why?

Kang

**Comment by im3sanger** [comment]
Hello Kang,

Thank you for your interest in dndscv. This is the correct output when running dndscv without indels. In the absence of indels, only substitutions are used and the global p-values and q-values are shown in the "pallsubs_cv" and "qallsubs_cv" columns, respectively.

Best wishes,
Inigo
