### ISSUE TITLE
issue about position of input file 

### ISSUE THREAD

**Issue by stroke1989** [im3sanger/dndscv#73]
excuse me:
when I used dndscv aiming to get significantly mutated genes, the input file it required should include  five columns (sampleID, chromosome, position, reference base and mutant base), however, as to the position , my data didn't have position column, but have **_start_** and **_end_**, instead, in this case, how do I preprocess my data to meet the input file requirement? Hope your reponse! Appreciate!

**Comment by im3sanger** [comment]
Hello,

Thanks for your interest in dNdScv. You can use the "start" position in the input table. dNdScv does not need the "end" position.

Best,
Inigo
