### ISSUE TITLE
Error when installing dndsv using: install_github("im3sanger/dndscv") 

### ISSUE THREAD

**Issue by sakrnference** [im3sanger/dndscv#75]
Hello,

I am getting this error when installing the dndscv package using the `install_github` from your instructions. 

  ```
`Installing package into ‘/usr/local/lib/R/site-library’
  (as ‘lib’ is unspecified)
  ERROR: dependencies ‘seqinr’, ‘Rsamtools’ are not available for package ‘dndscv’
  * removing ‘/usr/local/lib/R/site-library/dndscv’
  Warning messages:
  1: In i.p(...) :
    installation of package ‘Rhtslib’ had non-zero exit status
  2: In i.p(...) : installation of package ‘ade4’ had non-zero exit status
  3: In i.p(...) :
    installation of package ‘Rsamtools’ had non-zero exit status
  4: In i.p(...) : installation of package ‘seqinr’ had non-zero exit status
  5: In i.p(...) :
    installation of package ‘/tmp/RtmpADkjWb/file830f103e8f56/dndscv_0.0.1.0.tar.gz’ had non-zero exit status`
```

**Comment by biagoncalves** [comment]
Hi, @sakrnference 

I'm not sure, but it seems you need to install these dependencies first. 

You're using linux, right? I think  the first comment on this [issue](https://github.com/r-lib/devtools/issues/2131) may help you.

**Comment by sakrnference** [comment]
Thank you @biagoncalves. I have one more question please. Do you know where I can generate the CDS table for SARS-CoV-2 ? as it is not available in the link you kindly provided. Thank you

**Comment by im3sanger** [comment]
Hello,

Sorry for the late reply. You can download the RefCDS object for SARS-CoV-2 from this link (from the [dndscv_data](https://github.com/im3sanger/dndscv_data) repository): [RefCDS_MN908947.3.peptides.rda](https://github.com/im3sanger/dndscv_data/blob/master/data/RefCDS_MN908947.3.peptides.rda)

Best wishes,
Inigo

**Comment by sakrnference** [comment]
Thank you for your kind response. I was able to download it but I am having an issue when reading the rda file. I tried to convert the rda from a list to Dataframe and then read it using this table function `reftable = read.table(RefCDS, header=1, sep="\t", stringsAsFactors=F)` 
but am getting this error 
`Error in read.table(RefCDS, header = 1, sep = "\t", stringsAsFactors = F): 'file' must be a character string or connection`

as well I tried to run the buildref function on my .fasta sequence and the RefCDS object for SARS-Cov data using the following code:
`buildref(cdsfile=RefCDS, genomefile=data.file, outfile = "data_our_data_refcds.rda", excludechrs="MT")`
but I am getting this error

```
`[1/3] Preparing the environment...

Error in read.table(cdsfile, header = 1, sep = "\t", stringsAsFactors = F, : 'file' must be a character string or connection
Traceback:

1. buildref(cdsfile = RefCDS, genomefile = data.file, outfile = "data_our_data_refcds.rda", 
 .     excludechrs = "MT")
2. read.table(cdsfile, header = 1, sep = "\t", stringsAsFactors = F, 
 .     quote = "\"", na.strings = "-", fill = TRUE)
3. stop("'file' must be a character string or connection")`
```

Thank you so much and I hope you can please help me with this issue. Thank you so much

**Comment by im3sanger** [comment]
Hello,

The [RefCDS_MN908947.3.peptides.rda](https://github.com/im3sanger/dndscv_data/blob/master/data/RefCDS_MN908947.3.peptides.rda) file is already the output of buildref, not a transcript table.

You can run dNdScv on SARS-CoV-2 data using this command:
dndsout = dndscv(mutations, refdb = "RefCDS_MN908947.3.peptides.rda", cv =  NULL, max_muts_per_gene_per_sample = Inf, max_coding_muts_per_sample = Inf)

I hope this helps,
Inigo

**Comment by im3sanger** [comment]
I attach a transcript table here for your information.
[Reftable_MN908947.3_peptide_resolution.txt](https://github.com/im3sanger/dndscv/files/8087350/Reftable_MN908947.3_peptide_resolution.txt)
