### ISSUE TITLE
5-nucleotide context mutational signature

### ISSUE THREAD

**Issue by andreyurch** [im3sanger/dndscv#76]
Dear developers,

Thank you for the very useful tool. I am working with skin cancers and remember that in the original publication 3-nucleotide mutational signature was not enough to correct for DnDs values in melanoma. Is there a function in the package to use 5-nucleotide mutational signatures? I was not able to find this.

best regards,
Andrey

**Comment by im3sanger** [comment]
Dear Andrey,

Thank you for your interest. At the moment there is no support for a pentanucleotide model in dNdScv. Please note that the UV signature only causes a bias in dN/dS ratios on the order of 10% when using a full trinucleotide model. This is only problematic when using exome-wide dN/dS ratios to make inferences about the number of exome-wide driver mutations, as in Fig 5 of our [2017 Cell paper](https://pubmed.ncbi.nlm.nih.gov/29056346/). If this is what you are interested in, please send me an email.

However, for most other analyses, the default trinucleotide substitution model in dNdScv works well, including for driver discovery in melanomas and other skin cancers, as we showed in [Fig 2](https://els-jbs-prod-cdn.jbs.elsevierhealth.com/cms/attachment/e4154541-1127-4bf6-a179-2cb6a34b6d8d/gr2_lrg.jpg) of the "Universal patterns" paper or in our analysis of [normal skin](https://pubmed.ncbi.nlm.nih.gov/25999502/).

I hope this helps,
Inigo
