### ISSUE TITLE
dNdS script takes a lot of time to run 

### ISSUE THREAD

**Issue by sakrnference** [im3sanger/dndscv#79]
Hi,

I have 70K sequences in a FASTA file aligned to a reference genome. When I am running the dNdS script it takes about 9 hours to run for these 70K sequences. It takes even more time when increasing the number of sequences. My interpretation for this is that, I guess the runtime is exponential, since it has to compare the mutations with those in the other sequences, and then merge/extend the list of mutations. Is there any way that I can do optimize the process and generate the dNdS score for a large set of sequences faster ?

I am looking forward to hearing from you soon. 
Thank you so much

**Comment by im3sanger** [comment]
Hello,

I am not sure I understand your question. Which dNdS script are you referring to? None of the functions in the dNdScv package calculates dN/dS using fasta alignments.

Inigo

**Comment by sakrnference** [comment]
Hello Inigo,

Thank you for your response. Sorry If I wasn’t clear.

I am running dNdS on SARS-Cov-2. In order to run the dNdS script on SARS-Cov-2, it requires me to have 3 inputs, CDS transcript table for the reference genome, FASTA file that have the sequence for the reference genome, and a list of mutations that are aligned to the reference genome as we discussed in this issue here before https://github.com/im3sanger/dndscv_data/issues/2#issuecomment-1046666252 
However, when I have a large list of mutations, say 70K sequences, it takes about 9 hours to run.
I hope that make my question more clear.

Also, I want to clarify something, I saw in one of the previous issues https://github.com/im3sanger/dndscv/issues/64#issuecomment-847891342  
you kindly stated that the output of the dNdS score for the gene can be found in the (wmis_cv) column. Is that the dN/dS ratio or the MLE of the dN/dS ? And is it possible to get the values of the dN and dS separately please?

Thank you so much
 

> On May 5, 2022, at 5:34 AM, Inigo Martincorena ***@***.***> wrote:
> 
> ﻿
> Hello,
> 
> I am not sure I understand your question. Which dNdS script are you referring to? None of the functions in the dNdScv package calculates dN/dS using fasta alignments.
> 
> Inigo
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.

-- 
CONFIDENTIALITY NOTICE: This E-Mail is intended only for the individual or 
entity to which it is addressed and may contain information that is 
confidential. If you have received this communication in error, do not 
distribute. Please delete the original message and immediately notify the 
sender.

**Comment by sakrnference** [comment]
Hello Inigo,

I hope you are doing well.
I am just making sure you kindly received my last message.
Looking forward to hearing back from you soon.

Ziad Sakr

> On May 5, 2022, at 9:39 AM, Ziad Sakr ***@***.***> wrote:
> 
> ﻿
> Hello Inigo,
> 
> Thank you for your response. Sorry If I wasn’t clear.
> 
> I am running dNdS on SARS-Cov-2. In order to run the dNdS script on SARS-Cov-2, it requires me to have 3 inputs, CDS transcript table for the reference genome, FASTA file that have the sequence for the reference genome, and a list of mutations that are aligned to the reference genome as we discussed in this issue here before https://github.com/im3sanger/dndscv_data/issues/2#issuecomment-1046666252 
> However, when I have a large list of mutations, say 70K sequences, it takes about 9 hours to run.
> I hope that make my question more clear.
> 
> Also, I want to clarify something, I saw in one of the previous issues https://github.com/im3sanger/dndscv/issues/64#issuecomment-847891342  
> you kindly stated that the output of the dNdS score for the gene can be found in the (wmis_cv) column. Is that the dN/dS ratio or the MLE of the dN/dS ? And is it possible to get the values of the dN and dS separately please?
> 
> Thank you so much
>  
> 
>>> On May 5, 2022, at 5:34 AM, Inigo Martincorena ***@***.***> wrote:
>>> 
>> ﻿
>> Hello,
>> 
>> I am not sure I understand your question. Which dNdS script are you referring to? None of the functions in the dNdScv package calculates dN/dS using fasta alignments.
>> 
>> Inigo
>> 
>> —
>> Reply to this email directly, view it on GitHub, or unsubscribe.
>> You are receiving this because you authored the thread.

-- 
CONFIDENTIALITY NOTICE: This E-Mail is intended only for the individual or 
entity to which it is addressed and may contain information that is 
confidential. If you have received this communication in error, do not 
distribute. Please delete the original message and immediately notify the 
sender.

**Comment by im3sanger** [comment]
Hi Ziad,

Thank you for your email. Please note that the code that you are using was only a small example script that I posted as an answer to your previous question, but it is not part of the dNdScv package and not necesarily designed to scale up or to handle 70k sequences. The script simply loads an alignment file and uses a for loop to annotate the differences of each sequence to the first (reference) sequence. There are surely much faster ways to do so outside (or inside) R. You could also parallelise the computation if needed instead of processing 70k sequences in a for loop. But I am afraid I am not the best person to ask about how to do this faster.

Regarding your second question... I am not sure I understand it, wmis_cv is the dN/dS ratio for the gene, which is also a maximum likelihood estimate (MLE).

Best wishes,
Inigo
