### ISSUE TITLE
Error in while ((it <- it + 1) < limit && abs(del) > eps)

### ISSUE THREAD

**Issue by zhuhenan** [im3sanger/dndscv#83]
Hi,

I know you have dealt with this issue two years ago. But I just want to report my stupid setting that will trigger this error. 

I removed all my synonymous mutations for specific analysis before, and then fed only non-synonymous mutations table into the dndscv. "Error in while ((it <- it + 1) < limit && abs(del) > eps)" was showed as the same as previous one. 

Best,
Henan

**Comment by im3sanger** [comment]
Thank you, Henan!
