### ISSUE TITLE
How to verify the mutations are independent events?

### ISSUE THREAD

**Issue by Sunsq1997** [im3sanger/dndscv#84]

**Comment by im3sanger** [comment]
Hello,

Thank you for your interest in dNdScv. This is a warning message to remind the user that dNdScv assumes that each mutation in the input table is an independent mutational event. If you see the same somatic mutation in two different patients (e.g. in TCGA as in your case), they will be two independent mutations. However, if you see the same mutation in two regions of a given tumour, they are likely to be the same event (this could be formally confirmed using a phylogenetic analysis) and should be present only once in the input table.

I hope this helps,
Inigo
