### ISSUE TITLE
signif_genes = sel_cv[sel_cv$qglobal_cv<0.1, c("gene_name","qglobal_cv")]  error

### ISSUE THREAD

**Issue by HendrinaS** [im3sanger/dndscv#92]
Hi, could you please help with the following issue,

I keep getting an error when I run the flooring script signif_genes = sel_cv[sel_cv$qglobal_cv<0.1, c("gene_name","qglobal_cv")],. I don't know what it means, could you please explain to me on how to solve this?

my columns headings are as follow; 
 sampleID chr       pos ref alt    geneID
1   PD39448a   1  11883839   C   G     CLCN6
2   PD39448a   1  16736168   A   G   SPATA21

should I change the geneId column to gene_name?

**Comment by im3sanger** [comment]
Dear Hendrina,

Thank you for this question and your other question sent by email. I have replied to you by email.

Best,
Inigo
