### ISSUE TITLE
using which refCDS-hg38? doubt for covariate

### ISSUE THREAD

**Issue by complexgenome** [im3sanger/dndscv#95]
Hello there,

Hope this finds you well. Thank you for this tool.

I've Whole-exome data, hg38 human genome build. I downloaded data from https://github.com/im3sanger/dndscv_data/tree/master/data

I use the following code to have a first run:

```
dndsout = dndscv(df_mutation, refdb="RefCDS_human_GRCh38_GencodeV18_recommended.rda", cv=NULL)
print(dndsout$sel_cv)
```
It works and no issues.

I've some questions on using files with covariates. 

What covariates do I provide when I use `RefCDS_human_hg19_GencodeV18_newcovariates.rda` file? Or do I  provide cv=null when using this file?

There are no covariates for hg38 in the data shipped with library.

Sorry, the manual doesn't mention much on this. https://htmlpreview.github.io/?http://github.com/im3sanger/dndscv/blob/master/vignettes/buildref.html

Looking forward for your inputs.

**Comment by im3sanger** [comment]
Hello,

Please see this link for instructions: https://github.com/im3sanger/dndscv/issues/30#issuecomment-1000868593

Best,
Inigo
