### ISSUE TITLE
Can we calculate dN/dS ratio for each sample?

### ISSUE THREAD

**Issue by lincj1994** [im3sanger/dndscv#97]
Hi. I'm wondering if we can estimate the 𝑑𝑁/𝑑𝑆 ratio for each sample, where a ratio greater than 1 indicates that a sample may be eliminated by immune surveillance, and a ratio less than 1 suggests that a sample may escape immune surveillance.

**Comment by im3sanger** [comment]
Hello. No, I do not think that this analysis would be meaningful for several reasons. At a sample level, dN/dS ratios are noisy as they are estimated using small numbers of mutations (the substitution model will also contain considerable uncertainty). Also, the ability of a tumour to be elimited by (or escape) immune surveillance is likely dominated by key factors unrelated to dN/dS, such as overall mutation burden, presence of more neoantigenic mutations, immune evasion strategies, etc.

In theory, one should be able to use dN/dS ratios to look for evidence of negative selection at neoantigenic sites, as evidence of immune surveillance having acted in the evolution of a tumour. But it practice we have found very little or rather no signals of negative selection when we have attempted these analyses. Although I note that this is different from your suggestion above.
